{% set version = "8.2" %}
{% set actual_version = "8.2" %}

package:
  name: cdat_info
  version: {{ version }}

source:
    url: https://github.com/CDAT/cdat_info/archive/v{{ actual_version }}.tar.gz
    sha256: 2bcac2498a9e892793a9461e96f2736adb41500e0e371ea1f0a5bb9b659d686a

build:
  number: 3
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - nbformat
    - openssl >1.1

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: BSD
  license_file: bsd-3-clause.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - jasonb5
