{% set version = "8.0" %}

package:
  name: cdat_info
  version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdat_info/archive/v{{ version }}.tar.gz
    sha256: 7dd59358f2086920f9ac16fe292d5cafda6e2b0c21c2b0761e21f36228c82fdd

build:
  number: 1003
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - openssl >1.1

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: CCLRC
  license_file: LEGAL.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
