{% set version = "8.2" %}
{% set actual_version = "8.2" %}

package:
  name: cdat_info
  version: {{ version }}

source:
    url: https://github.com/CDAT/cdat_info/archive/v{{ actual_version }}.tar.gz
    sha256: 81b3d68d98ba03e9a3ce72367432c21b4fbb9497be13d12d901e16e24b656ad7

build:
  number: 6
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - requests
    - nbformat
    - openssl >1.1

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: BSD
  license_file: bsd-3-clause.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - jasonb5
    - xylar
