{% set version = "8.2.1.rc1" %}
{% set actual_version = "8.2.1.rc1" %}

package:
  name: cdat_info
  version: {{ version }}

source:
    url: https://github.com/CDAT/cdat_info/archive/v{{ actual_version }}.tar.gz
    sha256: 04e0ba7ab4ac573f05cfa7ba7f14e6237593fc9649830a5e8062be888b5381c2

build:
  number: 1
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - requests
    - nbformat
    - openssl >1.1

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: BSD
  license_file: bsd-3-clause.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - jasonb5
    - xylar
