{% set name = "cdat_info" %}
{% set version = "8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdat_info/archive/v{{ version }}.tar.gz
    sha256: 4af70b1c05fe151c1c6a2ad78ddfca51963841518defc0ce11dd5d63007a3cf2

build:
  number: 0
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - python
  run:
    - python
    - requests

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: CCLRC
  license_file: LEGAL.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
