appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: J75vUdJgtR9tVWRmmjG9SPifK42HoWXVbOUKL06NdCX9MDm/R3YO6aod3bY8MlnWzUW50hcVEj/vP7pWVjh6ZoZuX6fUYQn51A55Yq6Ml7q9igdIy5uMMZl4ygiMLCnBFPkPXMurn0hbvdQVlS9jVyq9adNXif6PFCKn3mqePRmLx/24HkQNE8HUAumzjjGbyhnw9aW4rveV2+D4N25zfLaEGh6R81o7fLX+XkioIEfDlW9RVyPguEXE0zWtWhi2lw7zStoDvsXmevxyrAcKxO8DUJsoIGIftefYJR6f09e2i8fJuO+vHF8Lcn/ZfuFJ30Fcjcndie47O3gkISu+MvQPEYVU4VwzEztn3VahyOLhI5c+Va5WS/rkqkTVCegzB47afRTs5lIWAzM6uCpQsRTOs2fLWuvArdcEK4P7xk7q17OEhJtPm8ntI28zt4PzqfDo4Z0w9Cj02Q3LSlqjCRiC7z7+GtmC2mFHEdZRoIhzGZFwnbi3stX4LthmAHrUNyc9EpQpln9DUmwdA429Bjsp+Yg9qcBS1pbxF3Oxt+wknnR9c8YDomeWLFZJ4ftGGs+mby9By5WOXrxr3k8wO1JXxSr5iSt7ekfsZ2imGwVd9zDSnLko829n2gqQItjpeMA/F0DdYqQqoxBB5D4punf4/xz0kMhdSUCuYy7sNOY=}
conda_forge_output_validation: true
