travis:
  secure:
    BINSTAR_TOKEN: poHxudxgQbIO1T8MPrq3E2Jw3Vw5E7McDi4acmgFCIIkj09y6sG+ZcE52xY0QZ+yBanbbgqbCSoZbDLpLQfdQWeqBFU7RMJepDYFLJXajTglehwyuJS0yunemtue0wzX+VnA36s7O8SuQrgatuI+dNjoo0CQ5gfjYNWvmPfieR5iwtXXh2olT5yj1+G6mOIPMncRX8eeSaEc9k8V+mf/uJDVKrG+z5nacWsJUPdICSqvUKrWA2pSFnjINQYE491MOm74xo1XBMd8+Mn8alrknh2do4eCf6bN/esNiu8mzHTfKY632ka2hxMlmTk2FwW8Nr9BEuaRrQAk/BGdDhT+1PiimpD5Vut+M4jkSZAHiC9W2kA3ohWO0OlEi0j16wZNLvxU5Z/MXgZzg4Dm+Z7FJWeVcKCV0eL8LpROqY3VzuKVvznAsvGay0hrRbD8AnPLU1hUTagpRxaQnQ21MO99RW1VEnfJYcuXaKSdO5bg22nctj0L3q9KEqvBsfEdaUMbY1H9q1lYDaGMymsExkakvNp58CG27G9unJJ02Y2bmLVoLir9jwH/9pOnne/F4V6biHVjFUfNWMpQCF72vN2/CIja2T9DFbs2iEGGdFBRm/7GJ5UWKiOyaMC7z/ZsCUkHIOU+S2ondJsrh/t4N+1eMt4ZKtz4G5HlcU3r1nwL1oE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
